apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h1772c5uw-go
  janus-idp.io/tekton: h1772c5uw-go
  backstage.io/kubernetes-id: h1772c5uw-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: h1772c5uw-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
