apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: h1772c5uw-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: h1772c5uw-go 
  name: h1772c5uw-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: h1772c5uw-go
    weight: 100 
