apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: h1772c5uw-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:93d38e3b731c62e5c84c6f4784d2a9d58a487e8a@sha256:1fe99590db9884185515e852490f2c603af5bd79ee12ba14f4d0a1473c506d7d
          name: container-image
